FROM nginx

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./ca.crt /etc/nginx/ca.crt
COPY ./ca.key /etc/nginx/ca.key
COPY ./ca.crl /etc/nginx/ca.crl
COPY ./https_cert.crt /etc/nginx/https_cert.crt
COPY ./https_cert.key /etc/nginx/https_cert.key