version: '3.4'

services:
  proxy:  
    image: nginx-core # Our custom NGINX Docker image 
    container_name: "nginxcore" # Name the service
    build:
      context: ./DockeredAspNetSample/nginx
      dockerfile: Dockerfile
    ports:
    - "80:80"
    - "443:443"
  dockeredaspnetsample:
    image: dockeredaspnetsample
    container_name: "dockeredaspnetsample"
    build:
      context: .
      dockerfile: DockeredAspNetSample/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
